{% set name = "nomad-camels-driver-thorlabs-K10CR1" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_').lower() }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 6d7606f8e9a4e5b7da528a496f89c1e1eb0423b0dc0ce2a1aae39dfbba05ebaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9.6
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9.6
    - pylablib
    - nomad-camels

test:
  imports:
    - nomad_camels_driver_thorlabs_K10CR1

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Instrument driver for the Thorlabs K10CR1 rotation mount for NOMAD-CAMELS
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
